# Default values for squid.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: jhidalgo3/squid
  tag: latest
  pullPolicy: Always
  # imagePullSecrets:

service:
  type: ClusterIP
  #  Specify IP to whitelist if needed
  #loadBalancerSourceRanges: ""
  # Specify external IP if needed
  #loadBalancerIP: ""
  port: 8888
  # annotations: {}

ingress:
  enabled: false
  annotations: 
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  path: /
  hosts:
    - proxy.k8s.jhidalgo3.me
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

config: |
  acl localnet src 0.0.0.1-0.255.255.255  # RFC 1122 "this" network (LAN)
  acl localnet src 10.0.0.0/8             # RFC 1918 local private network (LAN)
  acl localnet src 100.64.0.0/10          # RFC 6598 shared address space (CGN)
  acl localnet src 169.254.0.0/16         # RFC 3927 link-local (directly plugged) machines
  acl localnet src 172.16.0.0/12          # RFC 1918 local private network (LAN)
  acl localnet src 192.168.0.0/16         # RFC 1918 local private network (LAN)
  acl localnet src fc00::/7               # RFC 4193 local private network range
  acl localnet src fe80::/10              # RFC 4291 link-local (directly plugged) machines

  acl SSL_ports port 443
  acl Safe_ports port 80		# http
  acl Safe_ports port 21		# ftp
  acl Safe_ports port 443		# https
  acl Safe_ports port 70		# gopher
  acl Safe_ports port 210		# wais
  acl Safe_ports port 1025-65535	# unregistered ports
  acl Safe_ports port 280		# http-mgmt
  acl Safe_ports port 488		# gss-http
  acl Safe_ports port 591		# filemaker
  acl Safe_ports port 777		# multiling http
  acl CONNECT method CONNECT

  # Recommended minimum Access Permission configuration:
  #
  # Deny requests to certain unsafe ports
  http_access deny !Safe_ports

  # Only allow cachemgr access from localhost
  http_access allow localhost manager
  http_access deny manager

  http_access deny to_localhost

  http_access allow localnet
  http_access allow localhost

  # Squid normally listens to port 3128
  http_port 3128

  # Uncomment and adjust the following to add a disk cache directory.
  #cache_dir ufs /var/cache/squid 100 16 256

  # Leave coredumps in the first cache dir
  coredump_dir /var/cache/squid

  #
  # Add any of your own refresh_pattern entries above these.
  #
  refresh_pattern ^ftp:		1440	20%	10080
  refresh_pattern ^gopher:	1440	0%	1440
  refresh_pattern -i (/cgi-bin/|\?) 0	0%	0
  refresh_pattern .		0	20%	4320

  # Do not display squid version
  # httpd_suppress_version_string on

  # acl all src 0.0.0.0/0
  # http_access allow all
  
  url_rewrite_access deny CONNECT
  url_rewrite_access allow all

  acl k8s dst 10.0.0.0/8
  acl local-servers dstdomain .svc.cluster.local 
  cache_peer 192.168.2.8 parent 3128 0 no-query default
  
  always_direct allow k8s
  #always_direct allow local-servers
  never_direct deny local-servers
  never_direct allow all
  
  acl hasRequest has request
  access_log daemon:/var/log/squid/access.log squid hasRequest

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

releaseAntiAffinity: true

metrics:
  enabled: false
  serviceMonitor: false
  exporter:
    port: 9301
    resources: {}
    image:
      repository: boynux/squid-exporter
      tag: v1.8
      pullPolicy: IfNotPresent
